# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  twitter_consumer_key: "8TF9qptoTjm3j3EhI1a9jKFAi"
  twitter_consumer_secret: "IOxjwKiC4BHdvp1JMzAIKIgSo8uxtJcgDOqRFGQOjvIYneWuKQ"

development:
  <<: *default
  secret_key_base: 4e3c64dab971b23e379bf14251e445a88d934529713b7b71f4c0a05cfaa23a06efe35b0385ff3d010c33eba508eb2b93b0abbacb7f6b85103aecce9046382da0

test:
  <<: *default
  secret_key_base: 96a01a246bdaa853457e8deddca87bbbf34bc2a7325dbacc7f034da86f2fc8fd151c6385c369907f9f3a5a6aeae41ac44a82d0b156239c8c3c7b637f07c36614

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
